#!/bin/bash


sum() {
	return $(($1+$2))
}


for var in $@
do
	filename="$var"
	while IFS= read -r line; 
	do
		IFS=":"
		echo "$line"
		read -a strarr <<< "$line"
		echo "Value 1: ${strarr[0]}, Value 2: ${strarr[1]}"
		x=$(sum ${strarr[0]} ${strarr[1]})
		echo "${strarr[0]} + ${strarr[1]} = $?"
	done < "$filename"
	echo "--------------------"
done

