#!/bin/bash


sum_simple() {

	arr=("$@")
	ret=0
	for i in "${arr[@]}"; do
		ret=$(($ret+$i)) 
	done
}

sum_squared() {
	arr=("$@")
	ret=0
	for i in "${arr[@]}"; do
		sq=$(($i**2))
		ret=$(($ret+$sq)) 
	done
}

OLDIFS=$IFS
for var in $@
do
	filename="$var"
	length=0
	sum_xy=0
	error=0

	X=()
	Y=()

	if [[ -f "$var" ]]; then
		while IFS= read -r line; 
		do
			IFS=":"
			read -a strarr <<< "$line"

			X+=( "${strarr[0]}" )

			Y+=( "${strarr[1]}" )

			length=$(($length + 1))

		done < "$filename"

		sum_simple "${X[@]}"
		sum_x=$ret
		
		sum_simple "${Y[@]}"
		sum_y=$ret
		
		sum_squared "${X[@]}"
		sum_x2=$ret

		for (( i = 0; i < $length; i++ )); do
			xy=$((${X[$i]}*${Y[$i]}))
			sum_xy=$(($sum_xy+$xy))
		done

		tmp1=$(($(($length * $sum_xy))-$(($sum_x * sum_y))))
		tmp2=$(($(($length * $sum_x2))-$(($sum_x * $sum_x))))
		if [[ $(echo "$tmp2 == 0" | bc) -eq 1 ]]
		then
			a=0
			b=0
			c=0
		else
			a=$(bc <<< "scale=2;$tmp1/$tmp2")


			x=$(bc <<< "scale=2;$a*$sum_x")
			if [[ $(echo "$a < 0" | bc) -eq 1 ]]
			then
				tmp=$(bc <<< "scale=2;$x * -1")
				y=$(bc <<< "scale=2;$sum_y+$tmp")
			else
				y=$(bc <<< "scale=2;$sum_y-$x")
			fi
			b=$(bc <<< "scale=2;$y/$length")


			for (( i = 0; i < $length; i++ )); do
				var1=$(bc <<< "scale=2;$a*${X[$i]}")
				var2=$(bc <<< "scale=2;$var1+$b")
				var3=$(bc <<< "scale=2;${Y[$i]}-$var2")
				var4=$(bc <<< "scale=2;$var3*$var3")
				error=$(bc <<< "scale=2;$error+$var4")
			done

			c=1
		fi

		echo "FILE: $filename, a=$a b=$b c=$c err=$error"	
	fi
	
	
done
IFS=$OLDIFSs
